
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author win 10
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //setSize(800,500);
        //setVisible(true);
           // setSize(600,600);
           //setVisible(true);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jb1 = new javax.swing.JButton();
        p1 = new javax.swing.JPasswordField();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.yellow);
        getContentPane().setLayout(null);

        j1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        j1.setText("           LOGIN FORM");
        getContentPane().add(j1);
        j1.setBounds(460, 110, 190, 36);

        j2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        j2.setText("UserName");
        getContentPane().add(j2);
        j2.setBounds(230, 210, 190, 36);

        j3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        j3.setText("Password");
        getContentPane().add(j3);
        j3.setBounds(220, 310, 190, 36);

        t1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        t1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(t1);
        t1.setBounds(720, 210, 156, 36);

        jb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb1.setText("LOGIN");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        getContentPane().add(jb1);
        jb1.setBounds(520, 470, 106, 40);

        p1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(p1);
        p1.setBounds(720, 310, 162, 36);

        lb1.setBackground(java.awt.Color.red);
        lb1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 51, 51));
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lb1);
        lb1.setBounds(898, 225, 171, 13);

        lb2.setForeground(java.awt.Color.red);
        getContentPane().add(lb2);
        lb2.setBounds(906, 326, 162, 13);

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("SATKAR GIRLS HOSTEL ");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 20, 349, 50);
        getContentPane().add(filler1);
        filler1.setBounds(1069, 196, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\win 10\\Desktop\\background.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1180, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
if(t1.getText().trim().isEmpty() && p1.getText().trim().isEmpty()){
    lb1.setText("Username is Empty");
    lb2.setText("Password is Empty");
}     
else if(t1.getText().trim().isEmpty())
{
    lb1.setText("Username is empty");
}
     
else if(p1.getText().trim().isEmpty())
{
    lb2.setText("Password is empty");
}
       
else{
        String s1=t1.getText();
        String s2=p1.getText();
       if(s1.equals("admin") && s2.equals("pass"))
       {
           FeeD second=new FeeD();
           second.setVisible(true);
       }
       else
       {
           JOptionPane.showMessageDialog(null, "Wrong Passsword");
           
       }
}
    }//GEN-LAST:event_jb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jb1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
