
import java.awt.Color;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author win 10
 */
public class Room extends javax.swing.JFrame {

    /**
     * Creates new form Room
     */
    public Room() {
        //String rno=null,status=null;
      //  JButton b[][] = new JButton[2][10] ;
        initComponents();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/fee";
            String uid="root";
            String pwd="root";
            Connection con=DriverManager.getConnection(url, uid, pwd);
            String sql="select* from roomview";
           PreparedStatement ps=con.prepareStatement(sql);
           
           ResultSet rs=ps.executeQuery();
           table1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch(Exception e){
    e.printStackTrace();
}

        
        
        
        
        
        /*try{
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("driver loded");
            String url="jdbc:mysql://localhost:3306/fee";
            String uid="root";
            String pwd="root";
     Connection con = DriverManager.getConnection(url,uid,pwd);
       // String s="select rno from entry order by rno";
         String s="select rno,status from entry order by rno";
     
     
        PreparedStatement p=con.prepareStatement(s);
        ResultSet rs=p.executeQuery();
                            while(rs.next()){          
                         rno=rs.getString(1); 
                         status=rs.getString(2);
                            System.out.println(rno);
                            System.out.println(status);
                            if(status.equals(null))
                            {
                                
                             for(int i = 1 ; i <=2 ;i++)
                            {
                               for(int j = 1 ; j <=10; j++)
                                 {     
                           b[i][j] = new JButton(rno);
                           b[i][j].setLayout(new GridLayout(2,10));
                         //  b[i][j].setBounds(60, 400, 220, 30);
                         b[i][j].setBackground(Color.LIGHT_GRAY);
                         //b[i][j].addActionListener(this);
                         b[i][j].setSize(50,50);
                         p6.add(b[i][j]);
                         b[i][j].setEnabled(false);
                       
                            }
                            
                            }
        
                            }
                            }
   /*      for(int i = 1 ; i <=2 ;i++)
        {
        for(int j = 1 ; j <=10; j++)
        {
        
                         
                      for(int k=1;k<=10;k++)
                        {
                            while(rs.next()){          
                         rno=rs.getString(1);            
                         System.out.println(rno);
                         b[i][j] = new JButton(Integer.toString(k));
                         b[i][j].setLayout(new GridLayout(2,10));
                         //  b[i][j].setBounds(60, 400, 220, 30);
                         b[i][j].setBackground(Color.LIGHT_GRAY);
                         //b[i][j].addActionListener(this);
                         b[i][j].setSize(50,50);
                         p1.add(b[i][j]);
                         
                        if(rno.equals(Integer.toString(k))){
                            System.out.println("............................");
                               b[i][j].setEnabled(false);
                          break;
                        }
                        else{
                            b[i][j].setEnabled(true);
                            System.out.println(".xxxxxxxxxxxxxxx.............");
                        break;
                        }
                       
                     
                          }
                         
                        }
                      break;  
        }
                    break;
        }
        }
         catch(Exception e){
                e.printStackTrace(); 
                 }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p1.setLayout(new java.awt.GridLayout(10, 2, 2, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("   ROOM  LIST");

        table1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Floor", "Room No.", "Capacity", "Vacancy"
            }
        ));
        table1.setAlignmentX(1.0F);
        table1.setAlignmentY(1.0F);
        table1.setEnabled(false);
        table1.setGridColor(new java.awt.Color(0, 0, 0));
        table1.setInheritsPopupMenu(true);
        table1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table1.setRowHeight(25);
        table1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        table1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        table1.getTableHeader().setResizingAllowed(false);
        table1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(367, 367, 367)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel p1;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
